### ISSUE TITLE
一、说说你对闭包的理解

### ISSUE THREAD

**Issue by Simbachen** [Simbachen/self-learning-front-end#1]
* 说说你对闭包的理解
* 闭包有哪些使用场景
* 追问：JS垃圾回收机制，闭包会造成什么问题

**Comment by strengthhu** [comment]
# 理解

在 JS 中，只有函数的子函数才能读取内部的变量，简单理解闭包就是定义在函数内部的函数。
闭包最大的特点就是可以记住它诞生的环境。

# 使用

闭包有两个常见用途：一，暂存数据 二，封装对象的私有属性和方法
（此处要举例..）

# 问题

外层函数每次运行都会生成新的闭包，闭包又会保存外层函数的变量
这样会一直占用内存，造成性能问题

**Comment by 0x0ffff** [comment]
- 说说你对闭包的理解
  - 一个函数对其周围状态的引用捆绑在一起，这样的组合可以称为闭包
- 闭包有哪些使用场景
  - 创建私有变量
  - 延长函数生命周期
- 追问：JS垃圾回收机制，闭包会造成什么问题
  - 标记回收法，会造成变量无法回收，引起内存泄漏

**Comment by Simbachen** [comment]
* 说说你对闭包的理解
- 函数返回函数
- 高阶函数（类比React高阶组件，虽然不是同一个东西）
- 一块可以限制访问的作用域
- ...
- 随便秀，理解可以和项目经历结合起来说，背答案就难有加分了~

* 闭包使用场景
- 来个例子
```JavaScript
function man() {
 let theAge = 0
 function setAge(age) {
    theAge = age
  }
  function getAge(){
   return theAge
  }
  return {
    setAge,
    getAge
  }
}
```
- 防抖、节流函数
* 追问：JS垃圾回收机制，闭包会造成什么问题
引用计数和标记清除
现代浏览器都使用了标记-清除垃圾回收算法，正常使用闭包不会造成什么问题。在老IE浏览器中，GC机制设计的不合理，容易引起问题。

**Comment by santana2000** [comment]
- 闭包：并不是定义了一个规则，而是由js变量的作用域特征引伸出来的概念
- 应用场景：地图上绘制一条折线
1. 折线是由每个点位坐标的集合绘制而成的，即绘线需要一个数组作为参数，在增、删数组内的元素时，监听数组变化并通过回调函数来实时更新绘制的折线
2. 如果用户点错了，需要回退到上一步并清除当前点，此时，可以在监听绘制折线函数的外部调用删除元素的函数来实现对数组的动态修改
`function line(p){
    let poiArr = [];
    poiArr = p;
    function deleteLatest(){
        poiArr.pop();
        return poiArr
    }
    return deleteLatest;
};

function backUpStep(){
    let backUp = line([p0,p1,p2,p3]);
    backUp();
}`

**Comment by santana2000** [comment]
`function line(p){
    let poiArr = [];
    poiArr = p;
    function deleteLatest(){
        poiArr.pop();
        return poiArr
    }
    return deleteLatest;
};

function backUpStep(){
    let backUp = line([p0,p1,p2,p3]);
    backUp();
}`

**Comment by santana2000** [comment]
- 并不是定义了一个规则，而是由js变量的作用域特征引伸出来的概念
- 应用场景：在地图上绘制折线
1. 地图上的折线由多个点连接而成，只要有一个包含点位集合的数组就能绘制折线。可以在增、删数组元素时，监听数组的变化，然后通过回调函数动态地更新地图上的折线
2. 当用户点错时，需要回退到上一步并清除当错误点位，此时，可以通过删除函数（闭包）来修改点集数组并重新绘制折线
```
function line(p){
    let poiArr = [];
    poiArr = p;
    function deleteLatest(){
        poiArr.pop();
        return poiArr
    }
    return deleteLatest;
};

function backUpStep(){
    let backUp = line([p0,p1,p2,p3]);
    backUp();
}
```
