### ISSUE TITLE
三、箭头函数和普通函数有什么区别？

### ISSUE THREAD

**Issue by Simbachen** [Simbachen/self-learning-front-end#4]
* 箭头函数和普通函数有什么区别？

**Comment by 0x0ffff** [comment]
- 使用 `=>` 定义函数，不使用 `function`
- 不能作为构造函数，也就是不能 `new`
- `this` 是定义时候的对象
- 不能使用 `arguments` 对象

**Comment by strengthhu** [comment]
1. 没有 this
2. 没有 arguments 参数

自己只知道这两个，楼上概括的更详细，受教了
