### ISSUE TITLE
五、必会题：什么是防抖和节流？

### ISSUE THREAD

**Issue by Simbachen** [Simbachen/self-learning-front-end#6]
* 什么是防抖和节流？
* 用在什么场景？
* 选择一个来实现？

> 这个题无论是项目还是面试都要必会！

**Comment by Sxxiong** [comment]
防抖和节流都属于性能优化
防抖指处理短时间内多次触发只需要执行一次的操作, 节流指执行过程中不再重复执行的操作
比如监听浏览器页面滚动
//防抖
function scrollTo(){
    const scrollTop = document.body.scrollTop || document.documentElement.scrollTop;
    console.log('滚动条位置：' + scrollTop);
}
function antdShake(func, delay){
    let timer = null;
    return function (){
        if(timer){
            clearTimout(timer)
        }
        timer = setTimeout(func, delay)
    }
}
window.onscroll = antdShake(scrollTo, 200)
//节流
function throttle(func, delay){
    let state = true;
    return function(){
        if(!state){
            return false;
        }    
        state = false;
        setTimeout (()=>{
            func()
            state = true;
        }, delay)
    }
}
window.onscroll = throttle(scrollTo, 200)

**Comment by strengthhu** [comment]
### 暂时不会，以后再来搞清楚

```js
 function debounce(fn, wait) {
     let timer = null
     return function() {
         if(timer) 
             clearTimeout(timer)
         timer = setTimeout(() => fn.apply(this, arguments), wait)
     }
 }
```

**Comment by 0x0ffff** [comment]
```js
function debounce(method, context) {
  var timer = null
  return function() {
    clearTimeout(timer)
    timer = setTimeout(() => {
      method.call(context)
    }, 1000)
  }
}

function print() {
  console.log('hello world!')
}

window.onscroll = debounce(print) // 滚动停止 1000ms 打印 hello world
```
